/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AnalysisReportUpdateManyWithoutCoinsInput } from "./AnalysisReportUpdateManyWithoutCoinsInput";
import {
  ValidateNested,
  IsOptional,
  IsInt,
  Max,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { MarketDataUpdateManyWithoutCoinsInput } from "./MarketDataUpdateManyWithoutCoinsInput";
import { TransactionUpdateManyWithoutCoinsInput } from "./TransactionUpdateManyWithoutCoinsInput";

@InputType()
class CoinUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AnalysisReportUpdateManyWithoutCoinsInput,
  })
  @ValidateNested()
  @Type(() => AnalysisReportUpdateManyWithoutCoinsInput)
  @IsOptional()
  @Field(() => AnalysisReportUpdateManyWithoutCoinsInput, {
    nullable: true,
  })
  analysisReports?: AnalysisReportUpdateManyWithoutCoinsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  currency?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => MarketDataUpdateManyWithoutCoinsInput,
  })
  @ValidateNested()
  @Type(() => MarketDataUpdateManyWithoutCoinsInput)
  @IsOptional()
  @Field(() => MarketDataUpdateManyWithoutCoinsInput, {
    nullable: true,
  })
  marketDataItems?: MarketDataUpdateManyWithoutCoinsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  symbolField?: string | null;

  @ApiProperty({
    required: false,
    type: () => TransactionUpdateManyWithoutCoinsInput,
  })
  @ValidateNested()
  @Type(() => TransactionUpdateManyWithoutCoinsInput)
  @IsOptional()
  @Field(() => TransactionUpdateManyWithoutCoinsInput, {
    nullable: true,
  })
  transactions?: TransactionUpdateManyWithoutCoinsInput;
}

export { CoinUpdateInput as CoinUpdateInput };
